# Generated by Django 5.0.1 on 2024-01-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
